Message Send
{'temp': 21, 'light': 81, 'mois': 79, 'updatedTime': '04-20-2023 02:34:09 AM', 'humi': 65}

Connection aborted. Rebooting Raspberry Pi Pico W...PROBLEM IN THONNY'S BACK-END: Exception while handling 'Run' (ConnectionError: EOF).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.


Process ended with exit code 1.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "boot.py", line 21, in <module>
  File "main.py", line 39, in <module>
  File "ahtx0.py", line 43, in __init__
KeyboardInterrupt: 
Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "ahtx0.py", line 43, in __init__
KeyboardInterrupt: 
MicroPython v1.19.1-1016-gb525f1c9e on 2023-04-14; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> 

Connection lost -- EOF

Use Stop/Restart to reconnect.

Process ended with exit code 1.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "boot.py", line 11, in <module>
KeyboardInterrupt: 
Traceback (most recent call last):
  File "main.py", line 9, in <module>
KeyboardInterrupt: 
MicroPython v1.19.1-1016-gb525f1c9e on 2023-04-14; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> 
MicroPython v1.19.1-1016-gb525f1c9e on 2023-04-14; Raspberry Pi Pico W with RP2040

Type "help()" for more information.

>>> 
